valuesFilePath: ./values.yml
pipelines:
- name: far_pipeline
  configuration:
    jfrogCliVersion: 2
  steps:
    - name: test_step
      type: Bash
      execution:
        onStart:
          - echo {{ .Values.isTestPipeline }}
          - echo {"hello world"}
        
